development:
  adapter: postgresql
  encoding: unicode
  database: smartshopping_development
  pool: 5
  username: juan
  password: 304550766

test:
  adapter: postgresql
  encoding: unicode
  database: smartshopping_test
  pool: 5
  username: juan
  password: 304550766
